### PR TITLE
Geomancy: all content added.

### PR DESCRIPTION
**Pull request by BrunoCarvalhoPaula**
Code revision required. Unsure about the content of first 3 lines.

### CODE REVIEW

**Comment by atmafox** [comment]
needs the below added to `revised/characters.tex`:
```\subsection{Geomancy}
\input {revised/geomancy.tex}```

**Review by atmafox — CHANGES_REQUESTED** [review]
needs the below added to `revised/characters.tex`:
```
\subsection{Geomancy}
\input {revised/geomancy.tex}
```

**Comment by BrunoCarvalhoPaula** [comment]
I need to add the \tstatus{} tag to all status effects. gonna do it tomorrow, please dont merge before that.

**Comment by BrunoCarvalhoPaula** [comment]
Please discard this pull since everything entered the b-spelllist branch

**Comment by atmafox** [comment]
No longer necessary, b-spelllist merge caught this

**Pull request closed without merging**
