### PR TITLE
b-remaster: updates all jobs except wizard

### PR DESCRIPTION
**Pull request by BrunoCarvalhoPaula**
Includes change to:
Adept.tex : updated to the errata version
Alchemist.tex: updated to the playtest packet version
Archer.tex: updated to the playtest packet version
Artist.tex: updated to the errata version
berserker.tex: updated to the playtest packet version
blackmage.tex: updated to the errata version
defender.tex: initial type, plus updated to the errata version
druid.tex: updated to the errata version
engine.tex: minor english changes, new optional rule and updated with new "as interrupt" rule idea plus changes in examples for changed abilities and included mentions to "charge time"
fencer.tex: updated to the errata version
freelancer.tex: minor wording changes
monk.tex: updated to the errata version

### CODE REVIEW

**Comment by BrunoCarvalhoPaula** [comment]
Included changes to:
Phalanx.tex : updated to the playtest packet version
rogue.tex: updated to errata version
runeknight.tex: updated to the playtest packet version
setup.tex: added a optional rule
squire.tex: updated to the playtest packet version
timemage.tex:changed the first ability to new wording
whitemage.tex: changed the first ability to new wording.

**Comment by BrunoCarvalhoPaula** [comment]
First typesetting for warrior and updated the valefor summon (to match the new !Jump)

Only wizard left to do, gonna do it tomorrow.

**Review by WeaverThree — APPROVED** [review]
No apparent breaking problems. Merge this first, I think

**Comment by WeaverThree** [comment]
Actually I'm going to go ahead and merge things because I don't think there are any actual problems.

**Pull request merged**
