### PR TITLE
Squire first draft

### PR DESCRIPTION
**Pull request by BrunoCarvalhoPaula**
Wrote Squire abilities

### CODE REVIEW

**Review by atmafox — CHANGES_REQUESTED** [review]
Looking very good!  That said, there are a few typos and it's in the wrong place.  The file should be in `FFRPG4e/core/revised/` rather than just `FFRPG4e/`.  Other than that, each jobspec environment already provides "Specialties:" in bold so you don't need to include it in the line with \tability.
Also, for English readability diff is a much more readable shortening of difficulty than dif so I've been changing that in my files; if you'd rather it stay dif I'll change it back. (=
Couple of missing spaces after :s as well, and a couple of actions not wrapped in \taction{}.

Still, if I copy it into the squire.tex file used and try to compile it, it almost works -- `\crystal` always takes two arguments. `\crystal{earth}{12pt}` as an example.  I plan to improve that later so it'll be `\crystal[type=earth]` with an optional form `\crystal[type=earth,height=12pt]` but that will default to 12pt if not provided.  Just haven't gotten there yet.

**Review by WeaverThree — COMMENTED** [review]
Note that the broken \crystal is on line 53, it took me a while to find it.

**Review by WeaverThree — APPROVED** [review]
Just testing github's review features, don't mind me.

**Comment by BrunoCarvalhoPaula** [comment]
Please discard this pull since everything entered the b-spelllist branch

**Comment by atmafox** [comment]
no longer necessary, b-spelllist got this

**Pull request closed without merging**
